name: Docker Build and Run

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t chaostreff-potsdam/yaspp .

      - name: Run Docker container
        run: docker run --rm -v ${{ github.workspace }}:/workdir chaostreff-potsdam/yaspp

      - name: List generated files
        run: |
          echo "Generated files:"
          ls -la *.html *.xml 2>/dev/null || echo "No output files found"
          echo "File sizes:"
          du -h *.html *.xml 2>/dev/null || echo "No files to measure"

      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-website-${{ github.run_number }}
          path: |
            index.html
            feed.xml
            cccp.css
          retention-days: 30

      - name: Create tarball of website files
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: |
          tar -czf website.tar.gz index.html feed.xml cccp.css

      - name: Update latest release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Build
          body: |
            Latest build from master branch
            
            **Commit:** ${{ github.sha }}
            **Date:** ${{ github.event.head_commit.timestamp }}
            
            Download the tarball to get the latest version of the static website files.
          files: website.tar.gz
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
